export const httpCodes = Object.freeze({
  HTTP_CONTINUE: 100,
  HTTP_SWITCHING_PROTOCOLS: 101,
  HTTP_PROCESSING: 102,
  HTTP_OK: 200,
  HTTP_CREATED: 201,
  HTTP_ACCEPTED: 202,
  HTTP_NON_AUTHORITATIVE_INFORMATION: 203,
  HTTP_NO_CONTENT: 204,
  HTTP_RESET_CONTENT: 205,
  HTTP_PARTIAL_CONTENT: 206,
  HTTP_MULTI_STATUS: 207,
  HTTP_ALREADY_REPORTED: 208,
  HTTP_IM_USED: 226,
  HTTP_MULTIPLE_CHOICES: 300,
  HTTP_MOVED_PERMANENTLY: 301,
  HTTP_FOUND: 302,
  HTTP_SEE_OTHER: 303,
  HTTP_NOT_MODIFIED: 304,
  HTTP_USE_PROXY: 305,
  HTTP_RESERVED: 306,
  HTTP_TEMPORARY_REDIRECT: 307,
  HTTP_PERMANENT_REDIRECT: 308,
  HTTP_BAD_REQUEST: 400,
  HTTP_UNAUTHORIZED: 401,
  HTTP_PAYMENT_REQUIRED: 402,
  HTTP_FORBIDDEN: 403,
  HTTP_NOT_FOUND: 404,
  HTTP_METHOD_NOT_ALLOWED: 405,
  HTTP_NOT_ACCEPTABLE: 406,
  HTTP_PROXY_AUTHENTICATION_REQUIRED: 407,
  HTTP_REQUEST_TIMEOUT: 408,
  HTTP_CONFLICT: 409,
  HTTP_GONE: 410,
  HTTP_LENGTH_REQUIRED: 411,
  HTTP_PRECONDITION_FAILED: 412,
  HTTP_REQUEST_ENTITY_TOO_LARGE: 413,
  HTTP_REQUEST_URI_TOO_LONG: 414,
  HTTP_UNSUPPORTED_MEDIA_TYPE: 415,
  HTTP_REQUESTED_RANGE_NOT_SATISFIABLE: 416,
  HTTP_EXPECTATION_FAILED: 417,
  HTTP_UNPROCESSABLE_ENTITY: 422,
  HTTP_LOCKED: 423,
  HTTP_FAILED_DEPENDENCY: 424,
  HTTP_UPGRADE_REQUIRED: 426,
  HTTP_PRECONDITION_REQUIRED: 428,
  HTTP_TOO_MANY_REQUESTS: 429,
  HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  HTTP_INTERNAL_SERVER_ERROR: 500,
  HTTP_NOT_IMPLEMENTED: 501,
  HTTP_BAD_GATEWAY: 502,
  HTTP_SERVICE_UNAVAILABLE: 503,
  HTTP_GATEWAY_TIMEOUT: 504,
  HTTP_HTTP_VERSION_NOT_SUPPORTED: 505,
  HTTP_VARIANT_ALSO_NEGOTIATES: 506,
  HTTP_INSUFFICIENT_STORAGE: 507,
  HTTP_LOOP_DETECTED: 508,
  HTTP_NOT_EXTENDED: 510,
  HTTP_NETWORK_AUTHENTICATION_REQUIRED: 511,
});

const httpMessages = Object.freeze({
  [httpCodes.HTTP_CONTINUE]: 'Continue',
  [httpCodes.HTTP_SWITCHING_PROTOCOLS]: 'Switching Protocols',
  [httpCodes.HTTP_PROCESSING]: 'Processing',
  [httpCodes.HTTP_OK]: 'OK',
  [httpCodes.HTTP_CREATED]: 'Created',
  [httpCodes.HTTP_ACCEPTED]: 'Accepted',
  [httpCodes.HTTP_NON_AUTHORITATIVE_INFORMATION]: 'Non-Authoritative Information',
  [httpCodes.HTTP_NO_CONTENT]: 'No Content',
  [httpCodes.HTTP_RESET_CONTENT]: 'Reset Content',
  [httpCodes.HTTP_PARTIAL_CONTENT]: 'Partial Content',
  [httpCodes.HTTP_MULTI_STATUS]: 'Multi-Status',
  [httpCodes.HTTP_ALREADY_REPORTED]: 'Already Reported',
  [httpCodes.HTTP_IM_USED]: 'IM Used',
  [httpCodes.HTTP_MULTIPLE_CHOICES]: 'Multiple Choices',
  [httpCodes.HTTP_MOVED_PERMANENTLY]: 'Moved Permanently',
  [httpCodes.HTTP_FOUND]: 'Found',
  [httpCodes.HTTP_SEE_OTHER]: 'See Other',
  [httpCodes.HTTP_NOT_MODIFIED]: 'Not Modified',
  [httpCodes.HTTP_USE_PROXY]: 'Use Proxy',
  [httpCodes.HTTP_RESERVED]: 'Reserved',
  [httpCodes.HTTP_TEMPORARY_REDIRECT]: 'Temporary Redirect',
  [httpCodes.HTTP_PERMANENT_REDIRECT]: 'Permanent Redirect',
  [httpCodes.HTTP_BAD_REQUEST]: 'Bad Request',
  [httpCodes.HTTP_UNAUTHORIZED]: 'Unauthorized',
  [httpCodes.HTTP_PAYMENT_REQUIRED]: 'Payment Required',
  [httpCodes.HTTP_FORBIDDEN]: 'Forbidden',
  [httpCodes.HTTP_NOT_FOUND]: 'Not Found',
  [httpCodes.HTTP_METHOD_NOT_ALLOWED]: 'Method Not Allowed',
  [httpCodes.HTTP_NOT_ACCEPTABLE]: 'Not Acceptable',
  [httpCodes.HTTP_PROXY_AUTHENTICATION_REQUIRED]: 'Proxy Authentication Required',
  [httpCodes.HTTP_REQUEST_TIMEOUT]: 'Request Timeout',
  [httpCodes.HTTP_CONFLICT]: 'Conflict',
  [httpCodes.HTTP_GONE]: 'Gone',
  [httpCodes.HTTP_LENGTH_REQUIRED]: 'Length Required',
  [httpCodes.HTTP_PRECONDITION_FAILED]: 'Precondition Failed',
  [httpCodes.HTTP_REQUEST_ENTITY_TOO_LARGE]: 'Request Entity Too Large',
  [httpCodes.HTTP_REQUEST_URI_TOO_LONG]: 'Request-URI Too Long',
  [httpCodes.HTTP_UNSUPPORTED_MEDIA_TYPE]: 'Unsupported Media Type',
  [httpCodes.HTTP_REQUESTED_RANGE_NOT_SATISFIABLE]: 'Requested Range Not Satisfiable',
  [httpCodes.HTTP_EXPECTATION_FAILED]: 'Expectation Failed',
  [httpCodes.HTTP_UNPROCESSABLE_ENTITY]: 'Unprocessable Entity',
  [httpCodes.HTTP_LOCKED]: 'Locked',
  [httpCodes.HTTP_FAILED_DEPENDENCY]: 'Failed Dependency',
  [httpCodes.HTTP_UPGRADE_REQUIRED]: 'Upgrade Required',
  [httpCodes.HTTP_PRECONDITION_REQUIRED]: 'Precondition Required',
  [httpCodes.HTTP_TOO_MANY_REQUESTS]: 'Too Many Requests',
  [httpCodes.HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE]: 'Request Header Fields Too Large',
  [httpCodes.HTTP_INTERNAL_SERVER_ERROR]: 'Internal Server Error',
  [httpCodes.HTTP_NOT_IMPLEMENTED]: 'Not Implemented',
  [httpCodes.HTTP_BAD_GATEWAY]: 'Bad Gateway',
  [httpCodes.HTTP_SERVICE_UNAVAILABLE]: 'Service Unavailable',
  [httpCodes.HTTP_GATEWAY_TIMEOUT]: 'Gateway Timeout',
  [httpCodes.HTTP_HTTP_VERSION_NOT_SUPPORTED]: 'HTTP Version Not Supported',
  [httpCodes.HTTP_VARIANT_ALSO_NEGOTIATES]: 'Variant Also Negotiates (Experimental)',
  [httpCodes.HTTP_INSUFFICIENT_STORAGE]: 'Insufficient Storage',
  [httpCodes.HTTP_LOOP_DETECTED]: 'Loop Detected',
  [httpCodes.HTTP_NOT_EXTENDED]: 'Not Extended',
  [httpCodes.HTTP_NETWORK_AUTHENTICATION_REQUIRED]: 'Network Authentication Required',
});

export const getHttpMessage = httpCode => httpMessages[httpCode];
