version: "3"

services:
  mysql:
    image: mysql:5.6
    container_name: crypted_notes_dev_sql
    environment:
      - TZ=Europe/Madrid
      - MYSQL_DATABASE=crypted_notes
      - MYSQL_USER=crypted_notes-rw
      - MYSQL_PASSWORD=crypted_notes
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 5006:3306

  api:
    build: .
    container_name: crypted_notes_dev_api
    ports:
      - 5000:5000
    volumes:
      - .:/var/app/
      - /var/app/node_modules
    depends_on:
      - mysql
    environment:
      - PROJECT_NAME=crypted-notes
      - PORT=5000
      - DB_HOST=crypted_notes_dev_sql
      - DB_PORT=3306
      - DB_NAME=crypted_notes
      - DB_USER=crypted_notes-rw
      - DB_PASSWORD=crypted_notes
      - TEST_DB_HOST=crypted_notes_dev_test_sql
      - TEST_DB_PORT=3306
      - TEST_DB_NAME=test_crypted_notes
      - TEST_DB_USER=crypted_notes-rw
      - TEST_DB_PASSWORD=crypted_notes
